ALTER TABLE columns
ADD COLUMN category VARCHAR(50) NOT NULL DEFAULT 'TODO';

ALTER TABLE columns
ADD CONSTRAINT chk_column_category CHECK (category IN ('TODO', 'IN_PROGRESS', 'REVIEW', 'DONE'));

ALTER TABLE cards
ADD COLUMN is_done BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN completed_at TIMESTAMP WITH TIME ZONE DEFAULT NULL,
ADD COLUMN created_by UUID REFERENCES users(id) ON DELETE SET NULL;