// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Board struct {
	ID        uuid.UUID
	Title     string
	Budget    pgtype.Numeric
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type BoardMember struct {
	ID       uuid.UUID
	BoardID  uuid.UUID
	UserID   uuid.UUID
	Role     string
	JoinedAt pgtype.Timestamptz
}

type Card struct {
	ID             uuid.UUID
	ColumnID       uuid.UUID
	AssigneeID     pgtype.UUID
	Title          string
	Description    pgtype.Text
	EstimatedHours pgtype.Numeric
	Priority       pgtype.Text
	DueDate        pgtype.Date
	Position       float64
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type Column struct {
	ID        uuid.UUID
	BoardID   uuid.UUID
	Title     string
	Position  float64
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type TimeLog struct {
	ID           uuid.UUID
	CardID       uuid.UUID
	UserID       uuid.UUID
	HoursSpent   pgtype.Numeric
	CostIncurred pgtype.Numeric
	LoggedAt     pgtype.Timestamptz
}

type User struct {
	ID           uuid.UUID
	Email        string
	FullName     string
	HourlyRate   pgtype.Numeric
	PasswordHash pgtype.Text
	Provider     string
	ProviderID   pgtype.Text
	CreatedAt    pgtype.Timestamptz
}
