// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Activity struct {
	ID         string
	BoardID    string
	ActorID    string
	EventType  string
	EntityType string
	EntityID   *string
	Payload    []byte
	CreatedAt  time.Time
}

type Board struct {
	ID        string
	Title     string
	Budget    pgtype.Numeric
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type BoardMember struct {
	ID       string
	BoardID  string
	UserID   string
	Role     string
	JoinedAt pgtype.Timestamptz
}

type Card struct {
	ID             string
	ColumnID       string
	AssigneeID     *string
	Title          string
	Description    *string
	EstimatedHours pgtype.Numeric
	Priority       *string
	DueDate        *time.Time
	Position       float64
	CompletedAt    pgtype.Timestamptz
	CreatedBy      *string
	IsDone         bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type CardSubtask struct {
	ID        string
	CardID    string
	Title     string
	IsDone    bool
	Position  float64
	CreatedAt *time.Time
	UpdatedAt *time.Time
}

type CardTag struct {
	CardID string
	TagID  string
}

type Column struct {
	ID        string
	BoardID   string
	Title     string
	Position  float64
	Category  string
	Color     *string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Tag struct {
	ID        string
	BoardID   string
	Name      string
	Color     string
	CreatedAt pgtype.Timestamptz
}

type TimeLog struct {
	ID           string
	CardID       string
	UserID       string
	HoursSpent   pgtype.Numeric
	CostIncurred pgtype.Numeric
	LoggedAt     pgtype.Timestamptz
}

type User struct {
	ID           string
	Email        string
	FullName     string
	HourlyRate   pgtype.Numeric
	PasswordHash *string
	Provider     string
	ProviderID   *string
	CreatedAt    pgtype.Timestamptz
}
