// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Board struct {
	ID        pgtype.UUID
	Title     string
	Budget    pgtype.Numeric
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type Card struct {
	ID             pgtype.UUID
	ColumnID       pgtype.UUID
	AssigneeID     pgtype.UUID
	Title          string
	Description    pgtype.Text
	EstimatedHours pgtype.Numeric
	Priority       pgtype.Text
	DueDate        pgtype.Date
	Position       float64
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type Column struct {
	ID        pgtype.UUID
	BoardID   pgtype.UUID
	Title     string
	Position  float64
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type TimeLog struct {
	ID           pgtype.UUID
	CardID       pgtype.UUID
	UserID       pgtype.UUID
	HoursSpent   pgtype.Numeric
	CostIncurred pgtype.Numeric
	LoggedAt     pgtype.Timestamptz
}

type User struct {
	ID           pgtype.UUID
	Email        string
	FullName     string
	HourlyRate   pgtype.Numeric
	PasswordHash pgtype.Text
	Provider     string
	ProviderID   pgtype.Text
	CreatedAt    pgtype.Timestamptz
}
