// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addBoardMember = `-- name: AddBoardMember :one
INSERT INTO board_members (board_id, user_id, role)
VALUES ($1, $2, $3)
RETURNING id, board_id, user_id, role, joined_at
`

type AddBoardMemberParams struct {
	BoardID string
	UserID  string
	Role    string
}

func (q *Queries) AddBoardMember(ctx context.Context, arg AddBoardMemberParams) (BoardMember, error) {
	row := q.db.QueryRow(ctx, addBoardMember, arg.BoardID, arg.UserID, arg.Role)
	var i BoardMember
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const createBoard = `-- name: CreateBoard :one
INSERT INTO boards (id, title, created_at, updated_at)
VALUES (gen_random_uuid(), $1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
RETURNING id, title
`

type CreateBoardRow struct {
	ID    string
	Title string
}

func (q *Queries) CreateBoard(ctx context.Context, title string) (CreateBoardRow, error) {
	row := q.db.QueryRow(ctx, createBoard, title)
	var i CreateBoardRow
	err := row.Scan(&i.ID, &i.Title)
	return i, err
}

const createCard = `-- name: CreateCard :one
INSERT INTO cards (column_id, title, position, due_date, assignee_id, priority)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, column_id, title, description, position, due_date, assignee_id, priority
`

type CreateCardParams struct {
	ColumnID   string
	Title      string
	Position   float64
	DueDate    pgtype.Date
	AssigneeID pgtype.UUID
	Priority   *string
}

type CreateCardRow struct {
	ID          string
	ColumnID    string
	Title       string
	Description *string
	Position    float64
	DueDate     pgtype.Date
	AssigneeID  pgtype.UUID
	Priority    *string
}

func (q *Queries) CreateCard(ctx context.Context, arg CreateCardParams) (CreateCardRow, error) {
	row := q.db.QueryRow(ctx, createCard,
		arg.ColumnID,
		arg.Title,
		arg.Position,
		arg.DueDate,
		arg.AssigneeID,
		arg.Priority,
	)
	var i CreateCardRow
	err := row.Scan(
		&i.ID,
		&i.ColumnID,
		&i.Title,
		&i.Description,
		&i.Position,
		&i.DueDate,
		&i.AssigneeID,
		&i.Priority,
	)
	return i, err
}

const createColumn = `-- name: CreateColumn :one
INSERT INTO columns (id, board_id, title, position, created_at, updated_at)
VALUES (gen_random_uuid(), $1, $2, $3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
RETURNING id, board_id, title, position
`

type CreateColumnParams struct {
	BoardID  string
	Title    string
	Position float64
}

type CreateColumnRow struct {
	ID       string
	BoardID  string
	Title    string
	Position float64
}

func (q *Queries) CreateColumn(ctx context.Context, arg CreateColumnParams) (CreateColumnRow, error) {
	row := q.db.QueryRow(ctx, createColumn, arg.BoardID, arg.Title, arg.Position)
	var i CreateColumnRow
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Title,
		&i.Position,
	)
	return i, err
}

const createSubtask = `-- name: CreateSubtask :one
INSERT INTO card_subtasks (card_id, title, position)
VALUES ($1, $2, $3)
RETURNING id, card_id, title, is_done, position, created_at, updated_at
`

type CreateSubtaskParams struct {
	CardID   string
	Title    string
	Position float64
}

func (q *Queries) CreateSubtask(ctx context.Context, arg CreateSubtaskParams) (CardSubtask, error) {
	row := q.db.QueryRow(ctx, createSubtask, arg.CardID, arg.Title, arg.Position)
	var i CardSubtask
	err := row.Scan(
		&i.ID,
		&i.CardID,
		&i.Title,
		&i.IsDone,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, full_name, password_hash, provider, provider_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, email, full_name, hourly_rate, password_hash, provider, provider_id, created_at
`

type CreateUserParams struct {
	Email        string
	FullName     string
	PasswordHash *string
	Provider     string
	ProviderID   *string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.FullName,
		arg.PasswordHash,
		arg.Provider,
		arg.ProviderID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.HourlyRate,
		&i.PasswordHash,
		&i.Provider,
		&i.ProviderID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCard = `-- name: DeleteCard :exec
DELETE FROM cards WHERE id = $1
`

func (q *Queries) DeleteCard(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteCard, id)
	return err
}

const deleteSubtask = `-- name: DeleteSubtask :exec
DELETE FROM card_subtasks
WHERE id = $1
`

func (q *Queries) DeleteSubtask(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteSubtask, id)
	return err
}

const getAllActiveBoards = `-- name: GetAllActiveBoards :many
SELECT id, title, created_at 
FROM boards 
WHERE deleted_at IS NULL 
ORDER BY created_at DESC
`

type GetAllActiveBoardsRow struct {
	ID        string
	Title     string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) GetAllActiveBoards(ctx context.Context) ([]GetAllActiveBoardsRow, error) {
	rows, err := q.db.Query(ctx, getAllActiveBoards)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllActiveBoardsRow
	for rows.Next() {
		var i GetAllActiveBoardsRow
		if err := rows.Scan(&i.ID, &i.Title, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllBoards = `-- name: GetAllBoards :many
SELECT id, title, created_at 
FROM boards 
ORDER BY created_at DESC
`

type GetAllBoardsRow struct {
	ID        string
	Title     string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) GetAllBoards(ctx context.Context) ([]GetAllBoardsRow, error) {
	rows, err := q.db.Query(ctx, getAllBoards)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllBoardsRow
	for rows.Next() {
		var i GetAllBoardsRow
		if err := rows.Scan(&i.ID, &i.Title, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT id, email, full_name FROM users ORDER BY full_name ASC
`

type GetAllUsersRow struct {
	ID       string
	Email    string
	FullName string
}

func (q *Queries) GetAllUsers(ctx context.Context) ([]GetAllUsersRow, error) {
	rows, err := q.db.Query(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllUsersRow
	for rows.Next() {
		var i GetAllUsersRow
		if err := rows.Scan(&i.ID, &i.Email, &i.FullName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBoardByID = `-- name: GetBoardByID :one
SELECT id, title, budget, created_at, updated_at, deleted_at FROM boards 
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetBoardByID(ctx context.Context, id string) (Board, error) {
	row := q.db.QueryRow(ctx, getBoardByID, id)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Budget,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getBoardMemberRole = `-- name: GetBoardMemberRole :one
SELECT role FROM board_members
WHERE board_id = $1 AND user_id = $2
`

type GetBoardMemberRoleParams struct {
	BoardID string
	UserID  string
}

func (q *Queries) GetBoardMemberRole(ctx context.Context, arg GetBoardMemberRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, getBoardMemberRole, arg.BoardID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const getBoardMembers = `-- name: GetBoardMembers :many
SELECT 
    bm.id,
    bm.role,
    bm.joined_at,
    u.id       AS user_id,
    u.email,
    u.full_name
FROM board_members bm
JOIN users u ON bm.user_id = u.id
WHERE bm.board_id = $1
ORDER BY bm.joined_at ASC
`

type GetBoardMembersRow struct {
	ID       string
	Role     string
	JoinedAt pgtype.Timestamptz
	UserID   string
	Email    string
	FullName string
}

func (q *Queries) GetBoardMembers(ctx context.Context, boardID string) ([]GetBoardMembersRow, error) {
	rows, err := q.db.Query(ctx, getBoardMembers, boardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBoardMembersRow
	for rows.Next() {
		var i GetBoardMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Role,
			&i.JoinedAt,
			&i.UserID,
			&i.Email,
			&i.FullName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCard = `-- name: GetCard :one
SELECT id, column_id, assignee_id, title, description, estimated_hours, priority, due_date, position, created_at, updated_at FROM cards 
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetCard(ctx context.Context, id string) (Card, error) {
	row := q.db.QueryRow(ctx, getCard, id)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.ColumnID,
		&i.AssigneeID,
		&i.Title,
		&i.Description,
		&i.EstimatedHours,
		&i.Priority,
		&i.DueDate,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCardsByColumnIDs = `-- name: GetCardsByColumnIDs :many
SELECT 
    c.id,
    c.column_id,
    c.title,
    c.description,
    c.position,
    c.due_date,
    c.estimated_hours,
    c.assignee_id,
    c.priority,
    u.full_name AS assignee_name
FROM cards c
LEFT JOIN users u ON c.assignee_id = u.id
WHERE c.column_id = ANY($1::uuid[])
ORDER BY c.position ASC
`

type GetCardsByColumnIDsRow struct {
	ID             string
	ColumnID       string
	Title          string
	Description    *string
	Position       float64
	DueDate        pgtype.Date
	EstimatedHours pgtype.Numeric
	AssigneeID     pgtype.UUID
	Priority       *string
	AssigneeName   *string
}

func (q *Queries) GetCardsByColumnIDs(ctx context.Context, dollar_1 []string) ([]GetCardsByColumnIDsRow, error) {
	rows, err := q.db.Query(ctx, getCardsByColumnIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCardsByColumnIDsRow
	for rows.Next() {
		var i GetCardsByColumnIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.ColumnID,
			&i.Title,
			&i.Description,
			&i.Position,
			&i.DueDate,
			&i.EstimatedHours,
			&i.AssigneeID,
			&i.Priority,
			&i.AssigneeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getColumnsByBoardID = `-- name: GetColumnsByBoardID :many
SELECT id, board_id, title, position, created_at, updated_at
FROM columns 
WHERE board_id = $1 
ORDER BY position ASC
`

func (q *Queries) GetColumnsByBoardID(ctx context.Context, boardID string) ([]Column, error) {
	rows, err := q.db.Query(ctx, getColumnsByBoardID, boardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Column
	for rows.Next() {
		var i Column
		if err := rows.Scan(
			&i.ID,
			&i.BoardID,
			&i.Title,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubtask = `-- name: GetSubtask :one
SELECT id, card_id, title, is_done, position, created_at, updated_at FROM card_subtasks WHERE id = $1
`

// 🌟 (ถ้าคุณยังไม่มี Query สำหรับ GetSubtask ตัวเดียว ให้เพิ่มอันนี้เข้าไปด้วยครับ)
func (q *Queries) GetSubtask(ctx context.Context, id string) (CardSubtask, error) {
	row := q.db.QueryRow(ctx, getSubtask, id)
	var i CardSubtask
	err := row.Scan(
		&i.ID,
		&i.CardID,
		&i.Title,
		&i.IsDone,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubtasksByCardID = `-- name: GetSubtasksByCardID :many
SELECT id, card_id, title, is_done, position, created_at, updated_at FROM card_subtasks
WHERE card_id = $1
ORDER BY position ASC
`

func (q *Queries) GetSubtasksByCardID(ctx context.Context, cardID string) ([]CardSubtask, error) {
	rows, err := q.db.Query(ctx, getSubtasksByCardID, cardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CardSubtask
	for rows.Next() {
		var i CardSubtask
		if err := rows.Scan(
			&i.ID,
			&i.CardID,
			&i.Title,
			&i.IsDone,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTrashedBoards = `-- name: GetTrashedBoards :many
SELECT id, title, deleted_at 
FROM boards 
WHERE deleted_at IS NOT NULL 
ORDER BY deleted_at DESC
`

type GetTrashedBoardsRow struct {
	ID        string
	Title     string
	DeletedAt pgtype.Timestamptz
}

func (q *Queries) GetTrashedBoards(ctx context.Context) ([]GetTrashedBoardsRow, error) {
	rows, err := q.db.Query(ctx, getTrashedBoards)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTrashedBoardsRow
	for rows.Next() {
		var i GetTrashedBoardsRow
		if err := rows.Scan(&i.ID, &i.Title, &i.DeletedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, full_name, hourly_rate, password_hash, provider, provider_id, created_at FROM users WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.HourlyRate,
		&i.PasswordHash,
		&i.Provider,
		&i.ProviderID,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByProviderID = `-- name: GetUserByProviderID :one
SELECT id, email, full_name, hourly_rate, password_hash, provider, provider_id, created_at FROM users 
WHERE provider = $1 AND provider_id = $2 
LIMIT 1
`

type GetUserByProviderIDParams struct {
	Provider   string
	ProviderID *string
}

func (q *Queries) GetUserByProviderID(ctx context.Context, arg GetUserByProviderIDParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByProviderID, arg.Provider, arg.ProviderID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.HourlyRate,
		&i.PasswordHash,
		&i.Provider,
		&i.ProviderID,
		&i.CreatedAt,
	)
	return i, err
}

const hardDeleteBoard = `-- name: HardDeleteBoard :exec
DELETE FROM boards 
WHERE id = $1
`

// ลบข้อมูลออกจากตารางจริง (ถ้าตั้ง ON DELETE CASCADE ไว้ ลูกๆ จะหายไปด้วย)
func (q *Queries) HardDeleteBoard(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, hardDeleteBoard, id)
	return err
}

const moveBoardToTrash = `-- name: MoveBoardToTrash :exec
UPDATE boards 
SET deleted_at = CURRENT_TIMESTAMP 
WHERE id = $1
`

func (q *Queries) MoveBoardToTrash(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, moveBoardToTrash, id)
	return err
}

const removeBoardMember = `-- name: RemoveBoardMember :exec
DELETE FROM board_members
WHERE board_id = $1 AND user_id = $2
`

type RemoveBoardMemberParams struct {
	BoardID string
	UserID  string
}

func (q *Queries) RemoveBoardMember(ctx context.Context, arg RemoveBoardMemberParams) error {
	_, err := q.db.Exec(ctx, removeBoardMember, arg.BoardID, arg.UserID)
	return err
}

const restoreBoardFromTrash = `-- name: RestoreBoardFromTrash :exec
UPDATE boards 
SET deleted_at = NULL 
WHERE id = $1
`

func (q *Queries) RestoreBoardFromTrash(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, restoreBoardFromTrash, id)
	return err
}

const updateBoard = `-- name: UpdateBoard :one
UPDATE boards 
SET title = $2, 
    budget = $3,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, title, budget, created_at, updated_at, deleted_at
`

type UpdateBoardParams struct {
	ID     string
	Title  string
	Budget pgtype.Numeric
}

func (q *Queries) UpdateBoard(ctx context.Context, arg UpdateBoardParams) (Board, error) {
	row := q.db.QueryRow(ctx, updateBoard, arg.ID, arg.Title, arg.Budget)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Budget,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateBoardMemberRole = `-- name: UpdateBoardMemberRole :one
UPDATE board_members
SET role = $3
WHERE board_id = $1 AND user_id = $2
RETURNING id, board_id, user_id, role, joined_at
`

type UpdateBoardMemberRoleParams struct {
	BoardID string
	UserID  string
	Role    string
}

func (q *Queries) UpdateBoardMemberRole(ctx context.Context, arg UpdateBoardMemberRoleParams) (BoardMember, error) {
	row := q.db.QueryRow(ctx, updateBoardMemberRole, arg.BoardID, arg.UserID, arg.Role)
	var i BoardMember
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const updateCard = `-- name: UpdateCard :one
UPDATE cards
SET
    title            = COALESCE($2, title),
    description      = COALESCE($3, description),
    due_date         = COALESCE($4, due_date),
    assignee_id      = COALESCE($5, assignee_id),
    priority         = COALESCE($6, priority),
    estimated_hours  = COALESCE($7, estimated_hours),
    updated_at       = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, column_id, assignee_id, title, description, estimated_hours, priority, due_date, position, created_at, updated_at
`

type UpdateCardParams struct {
	ID             string
	Title          string
	Description    *string
	DueDate        pgtype.Date
	AssigneeID     pgtype.UUID
	Priority       *string
	EstimatedHours pgtype.Numeric
}

func (q *Queries) UpdateCard(ctx context.Context, arg UpdateCardParams) (Card, error) {
	row := q.db.QueryRow(ctx, updateCard,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.DueDate,
		arg.AssigneeID,
		arg.Priority,
		arg.EstimatedHours,
	)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.ColumnID,
		&i.AssigneeID,
		&i.Title,
		&i.Description,
		&i.EstimatedHours,
		&i.Priority,
		&i.DueDate,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCardColumn = `-- name: UpdateCardColumn :exec
UPDATE cards
SET column_id = $1, position = $2, updated_at = NOW()
WHERE id = $3
`

type UpdateCardColumnParams struct {
	ColumnID string
	Position float64
	ID       string
}

func (q *Queries) UpdateCardColumn(ctx context.Context, arg UpdateCardColumnParams) error {
	_, err := q.db.Exec(ctx, updateCardColumn, arg.ColumnID, arg.Position, arg.ID)
	return err
}

const updateSubtask = `-- name: UpdateSubtask :one
UPDATE card_subtasks
SET 
    title = COALESCE($2, title),
    is_done = COALESCE($3, is_done),
    position = COALESCE($4, position),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, card_id, title, is_done, position, created_at, updated_at
`

type UpdateSubtaskParams struct {
	ID       string
	Title    string
	IsDone   bool
	Position float64
}

func (q *Queries) UpdateSubtask(ctx context.Context, arg UpdateSubtaskParams) (CardSubtask, error) {
	row := q.db.QueryRow(ctx, updateSubtask,
		arg.ID,
		arg.Title,
		arg.IsDone,
		arg.Position,
	)
	var i CardSubtask
	err := row.Scan(
		&i.ID,
		&i.CardID,
		&i.Title,
		&i.IsDone,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSubtaskDone = `-- name: UpdateSubtaskDone :exec
UPDATE card_subtasks
SET 
    title = $2,
    is_done = $3,
    position = $4,
    updated_at = NOW()
WHERE id = $1
RETURNING id, card_id, title, is_done, position, created_at, updated_at
`

type UpdateSubtaskDoneParams struct {
	ID       string
	Title    string
	IsDone   bool
	Position float64
}

func (q *Queries) UpdateSubtaskDone(ctx context.Context, arg UpdateSubtaskDoneParams) error {
	_, err := q.db.Exec(ctx, updateSubtaskDone,
		arg.ID,
		arg.Title,
		arg.IsDone,
		arg.Position,
	)
	return err
}

const upsertOAuthUser = `-- name: UpsertOAuthUser :one
INSERT INTO users (email, full_name, provider, provider_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT (email) 
DO UPDATE SET 
    full_name = EXCLUDED.full_name,
    provider_id = EXCLUDED.provider_id
RETURNING id, email, full_name, hourly_rate, password_hash, provider, provider_id, created_at
`

type UpsertOAuthUserParams struct {
	Email      string
	FullName   string
	Provider   string
	ProviderID *string
}

func (q *Queries) UpsertOAuthUser(ctx context.Context, arg UpsertOAuthUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertOAuthUser,
		arg.Email,
		arg.FullName,
		arg.Provider,
		arg.ProviderID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.HourlyRate,
		&i.PasswordHash,
		&i.Provider,
		&i.ProviderID,
		&i.CreatedAt,
	)
	return i, err
}
