// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBoard = `-- name: CreateBoard :one
INSERT INTO boards (title, budget)
VALUES ($1, $2)
RETURNING id, title, budget, created_at, updated_at
`

type CreateBoardParams struct {
	Title  string
	Budget pgtype.Numeric
}

func (q *Queries) CreateBoard(ctx context.Context, arg CreateBoardParams) (Board, error) {
	row := q.db.QueryRow(ctx, createBoard, arg.Title, arg.Budget)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Budget,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createColumn = `-- name: CreateColumn :one
INSERT INTO columns (board_id, title, position)
VALUES ($1, $2, $3)
RETURNING id, board_id, title, position, created_at
`

type CreateColumnParams struct {
	BoardID  pgtype.UUID
	Title    string
	Position float64
}

func (q *Queries) CreateColumn(ctx context.Context, arg CreateColumnParams) (Column, error) {
	row := q.db.QueryRow(ctx, createColumn, arg.BoardID, arg.Title, arg.Position)
	var i Column
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Title,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const listBoards = `-- name: ListBoards :many
SELECT id, title, budget, created_at, updated_at FROM boards
ORDER BY created_at DESC
`

func (q *Queries) ListBoards(ctx context.Context) ([]Board, error) {
	rows, err := q.db.Query(ctx, listBoards)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Board
	for rows.Next() {
		var i Board
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Budget,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCardColumn = `-- name: UpdateCardColumn :exec
UPDATE cards
SET column_id = $1, position = $2, updated_at = NOW()
WHERE id = $3
`

type UpdateCardColumnParams struct {
	ColumnID pgtype.UUID
	Position float64
	ID       pgtype.UUID
}

func (q *Queries) UpdateCardColumn(ctx context.Context, arg UpdateCardColumnParams) error {
	_, err := q.db.Exec(ctx, updateCardColumn, arg.ColumnID, arg.Position, arg.ID)
	return err
}
